export const JOINTS = [
  { n: 1,  id: "head_proximal",     label: "head proximal" },
  { n: 2,  id: "head_centre",       label: "centre of head" },
  { n: 3,  id: "chin",              label: "chin" },
  { n: 4,  id: "manubrium",         label: "manubrium" },
  { n: 5,  id: "sacral_promontory", label: "sacral promontory" },
 
  { n: 6,  id: "shoulder_l",        label: "left shoulder" },
  { n: 7,  id: "elbow_l",           label: "left elbow" },
  { n: 8,  id: "wrist_l",           label: "left wrist" },
  { n: 9,  id: "fingertips_l",      label: "left fingertips" },
  { n: 10, id: "ilium_superior_l",  label: "left ilium superior" },
  { n: 11, id: "ischium_l",         label: "left ischium" },
  { n: 12, id: "acetabulum_l",      label: "left acetabulum" },
  { n: 13, id: "knee_l",            label: "left knee" },
  { n: 14, id: "ankle_l",           label: "left ankle" },
  { n: 15, id: "toes_l",            label: "left toes" },
 
  { n: 16, id: "shoulder_r",        label: "right shoulder" },
  { n: 17, id: "elbow_r",           label: "right elbow" },
  { n: 18, id: "wrist_r",           label: "right wrist" },
  { n: 19, id: "fingertips_r",      label: "right fingertips" },
  { n: 20, id: "ilium_superior_r",  label: "right ilium superior" },
  { n: 21, id: "ischium_r",         label: "right ischium" },
  { n: 22, id: "acetabulum_r",      label: "right acetabulum" },
  { n: 23, id: "knee_r",            label: "right knee" },
  { n: 24, id: "ankle_r",           label: "right ankle" },
  { n: 25, id: "toes_r",            label: "right toes" },
];